language: csharp
mono:
- 5.14.0
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode6.4
compiler:
- clang
- gcc
script:
- mono --version
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make prepare && make ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make prepare && make ; fi